- hosts: tags_items___db__
  name: Prepare storage for mysql.
  become: yes
  
  tasks:
    - name: Format the persistent disk
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-db-backup
        
    - name: Mount the persistent disk
      ansible.posix.mount:
        path: /var/lib/mysql
        src: /dev/disk/by-id/google-db-backup
        fstype: ext4
        state: mounted
    
    - name: Install mariadb and python3
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - mariadb-server
          - python3-pymysql    

    - name: Grant all priviliges to mediawiki user
      community.mysql.mysql_query:
        login_user: root
        query: "GRANT ALL ON mediawiki.* TO 'mediawiki'@'%' IDENTIFIED BY 'mediawiki';"
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Configure MariaDB to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Restart mariadb

  handlers:
    - name: Restart mariadb
      ansible.builtin.service:
        name: mariadb
        state: restarted


- hosts: tags_items___web__
  name: Prepare web instance for mediawiki.
  become: yes
  tasks: 
    - name: Install Apache, php, mediawiki, python3.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - mediawiki
          - python3-pymysql